---
- name: restart-wireguard
  service:
    name: wg-quick@wg0.service
    state: restarted

- name: sysctl flush ipv4 route table
  sysctl:
    name: net.ipv4.route.flush
    value: 1
    sysctl_set: true
