- name: Setup Radius service for remote authentication
  gather_facts: True
  hosts: radius
  become: true
  tasks:
    - import_tasks: roles/base/main.yml
    - include_role:
        name: radius
        tasks_from: install-freeradius-server.yml
    - include_role:
        name: radius
        tasks_from: configure-default-clients.yml
