- name: Setup VPN service by the first step
  gather_facts: True
  hosts: vpn_first_step
  tasks:
    - import_tasks: roles/base/main.yml
    - include_role:
        name: vpn
        tasks_from: install-wireguard-server.yml
    - include_role:
        name: vpn
        tasks_from: configure-default-clients.yml
